- frontend/forum-app/angular.json
- frontend/forum-app/package-lock.json
- frontend/forum-app/package.json
- frontend/forum-app/src/app/app.component.css
- frontend/forum-app/src/app/app.component.html
- frontend/forum-app/src/app/app.module.ts
- frontend/forum-app/src/app/header/header.component.html
- frontend/forum-app/src/app/header/header.component.ts
- frontend/forum-app/src/app/ng-material/ng-material.module.ts
- frontend/forum-app/src/index.html
- frontend/forum-app/src/styles.css
Changed to angular material buttons and input fields
> fix: changed frontend to angular material

- backend/configs/response.go
- backend/default_env.txt
- backend/users/models.go
- backend/users/service.go
> feat: added endpoint to check duplicate username

- backend/configs/JWTAuthentication.go
- backend/configs/LoginService.go
- backend/go.mod
- backend/go.sum
- backend/users/JWTMiddleware.go
- backend/users/service.go
Added logic for auth - generate a token, validate a token.
integrated it to the existing login API.
> feat: added jwt authentication to login

- frontend/forum-app/src/app/app.module.ts
- frontend/forum-app/src/app/header/header.component.html
- frontend/forum-app/src/app/navbar/navbar.component.html
- frontend/forum-app/src/app/navbar/navbar.component.spec.ts
- frontend/forum-app/src/app/navbar/navbar.component.ts
- frontend/forum-app/src/app/ng-material/ng-material.module.ts
> feat: added navbar

- frontend/forum-app/src/app/app-routing.module.ts
- frontend/forum-app/src/app/app.component.css
- frontend/forum-app/src/app/app.component.html
- frontend/forum-app/src/app/app.module.ts
- frontend/forum-app/src/app/header/header.component.css
- frontend/forum-app/src/app/header/header.component.html
- frontend/forum-app/src/app/header/header.component.ts
- frontend/forum-app/src/app/home/home.component.html
- frontend/forum-app/src/app/home/home.component.spec.ts
- frontend/forum-app/src/app/home/home.component.ts
- frontend/forum-app/src/app/login/login.component.html
- frontend/forum-app/src/app/login/login.component.spec.ts
- frontend/forum-app/src/app/login/login.component.ts
- frontend/forum-app/src/app/navbar/navbar.component.css
- frontend/forum-app/src/app/navbar/navbar.component.html
- frontend/forum-app/src/app/popup-message/popup-message.component.html
- frontend/forum-app/src/app/posts/posts.component.css
- frontend/forum-app/src/app/profile/profile.component.html
- frontend/forum-app/src/app/profile/profile.component.spec.ts
- frontend/forum-app/src/app/profile/profile.component.ts
- frontend/forum-app/src/app/subreddits.service.spec.ts
- frontend/forum-app/src/app/subreddits.service.ts
- frontend/forum-app/src/app/subreddits/subreddits.component.html
- frontend/forum-app/src/app/subreddits/subreddits.component.spec.ts
- frontend/forum-app/src/app/subreddits/subreddits.component.ts
Added placeholders for future pages
> Updated navigation bar

- Sprint1.md
> Spring1 Update

- frontend/forum-app/src/app/app.module.ts
- frontend/forum-app/src/app/ng-material/ng-material.module.ts
- frontend/forum-app/src/app/posts.service.ts
- frontend/forum-app/src/app/posts/posts.component.html
- frontend/forum-app/src/app/signup.service.ts
- frontend/forum-app/src/app/web-request.service.ts
Posts are now shown through cards and not just text.
Posts use json formatting to retrieve information.
No backend connection yet.
> Fix: changed post visuals

- backend/configs/JWTAuthentication.go
- backend/configs/dbSetup.go
- backend/configs/env.go
- backend/users/models.go
- backend/users/service.go
- Refactored code to improve readability by reformatting long lines to shorter well formatted blocks.
- Removed panic when no ".env" file is found and added fatal logging when no secret key is present in the environment.
> refactored code for improved readability, improved security for secret key

- backend/users/service.go
- frontend/forum-app/.browserslistrc
- Signup db call moved to a separate function to adhere better to DRY & KISS (Do not repeat yourself, Keep it simple silly)
- Http codes changed to 400 when request is bad, validation fails, message is now "failure" if there's no server error.
- Angular bug [(Safari browser version parsing bug)](https://github.com/angular/angular-cli/issues/22606) resolved by editing browserlistrc file as mentioned [here](https://github.com/angular/angular-cli/issues/22606#issuecomment-1032166126).
> fix,refactor: fixed http codes and error messages, moved signup db query to separate function, angular build bug

- backend/users/models.go
- backend/users/service.go
Added function, and modified the user models to be in tandem with the front-end user schemas.
closes #60
> feat: returning user details in the login response 

- backend/users/service.go
> fix: checks if user already exists in the signup API

- backend/communities/models.go
- backend/communities/service.go
- backend/users/service.go
- go.mod
- package-lock.json
Changes:
- New API to retrieve Community Details.
- Added check for whether community with same name exists prior to creating it.
- removed unused files (go.mod, package-lock.json in root folders).
Closes #66
> feat,fix: added get community details api, checking if community exists

- backend/main.go
- backend/posts/models.go
- backend/posts/service.go
- backend/users/models.go
- backend/users/service.go
created an API for the creation of post for any community with valid user credentials #43
> feat: create post API

- backend/posts/models.go
- backend/posts/service.go
- backend/profiles/models.go
> feat: GetAllPosts API to fetch all posts for specific user in a community

- backend/common/error_msgs.go
- backend/common/response.go
- backend/common/success_msgs.go
- backend/communities/models.go
- backend/communities/service.go
- backend/posts/models.go
- backend/posts/service.go
- backend/users/service.go
Changes:
- Added new APIs for Checking if Community with same name exists, Editing Community, Deleting Community.
- Moved responses to new package, and refactored all services.
- Changed response key names (like "data" to "error" for error responses).
Closes #47 and #58 
TODO: Add a check for authorized deletion of Community after JWT integration is complete.
> feat,refactor: added check-name, edit, delete community apis, moved responses to new pkg

- backend/posts/service.go
The previous version was problematic due to the schema of posts in the DB, now it's sorted according to the models decided by the backend recently
> fix: GetAllPosts API is fixed

- backend/communities/service.go
- backend/configs/dbSetup.go
- backend/go.mod
- backend/go.sum
- backend/main.go
- backend/posts/service.go
- backend/routes/routes.go
- backend/test_utils/constants.go
- backend/test_utils/make_request.go
- backend/tests/Readme.md
- backend/tests/main_test.go
- backend/tests/ping_test.go
- backend/tests/users_test.go
- backend/users/service.go
- Added Testing package and Acceptance Tests.
- Moved Router creation and routes adding code to a new package "routes".
Closes #78
>  feat,refactor,test: added acceptance and unit testing, added routes package

- backend/profiles/models.go
- backend/profiles/service.go
- backend/users/models.go
- backend/users/service.go
1.  Cleaned the code in user API for CreateProfile API to be called #70 
2. Added functions to convert the UserDB model to the ProfileDB model.
3. Added models. go for profile and function to create a document in profile collection on mongo server.
> feat: created profile API, integrated into signup API

- backend/posts/service.go
- backend/profiles/models.go
- backend/profiles/service.go
- backend/routes/routes.go
- backend/tests/posts_test.go
- backend/users/models.go
1. The front-end will be able to fetch profile details using the username #95 
2. the code for the post is now refactored and the readability of the code has been improved
3. the go-test for post and environment setup has been created
> feat,gotest,refactor: GetProfile API created, go-test for posts, improved readability

- backend/profiles/models.go
- backend/profiles/service.go
1.  the profile details can be updated now using the edit profile API. #97 
2.  improved the readability of conversion functions in profile/models
> feat: profile details for a username can be updated using EditProfile API

- backend/communities/models.go
- backend/communities/service.go
- backend/profiles/models.go
1.  created API to get all communities for a user integrated this API into the existing API GetCommunity, so the existing API was modified completely. #105 
2. The GetProfile is now returning information like karma and birthday that wasn't included before. #104 
3. The API to get all posts for a community was created #103 
4. improved the readability of the code in communities as changing the function placement
5. Modified the models in communities to include post model to avoid dependency on posts - will be visited again in sprint 3
> feat, fix: GetAllCommunities API created, API created to GetAllposts for a community, GetProfile API

- backend/posts/service.go
1. API has been created to fetch all of the posts to be displayed on the home page. #107 
2.  The previous API to get all posts for a community has been separately integrated into the communities, the GetAllPosts has been implemented in the posts [Note: will be moved to home soon in Sprint 3]
> feat: API to fetch all posts for the home page

- Sprint2.md
1. Explained user stories for sprint2
2. Explained some functionalities moved to sprint 3 because token authentication moved to sprint 3.
3. Created front-end document template including user stories and functionalities for the backend.
> docs: created sprint2.md explaining functionalities and user stories

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/user-story.md
Two Issue templates added for use from Sprint 3 on-wards.
Templates:
- User Story (Feature Request)
- Bug report
> docs: update issue templates

- frontend/forum-app/package-lock.json
- frontend/forum-app/package.json
- frontend/forum-app/src/app/login/login.component.html
- frontend/forum-app/src/app/login/login.component.ts
- frontend/forum-app/src/app/storage.ts
- package-lock.json
- package.json
Uses local storage to store user login status and session state
> feat: added login state per session

- backend/communities/models.go
- backend/communities/service.go
- backend/posts/models.go
- backend/posts/service.go
1.  Create feed API #147 
2.  Create mode like latest, hot as order by
3.  Handle edges cases for the API like a page being negative value etc. #156
> feat, bugfix: Feed API to fetch posts in a paginated manner

- backend/posts/service.go
- backend/profiles/service.go
> enhancement: FeedAPI URL method changed to POST from GET

- backend/communities/service.go
- backend/profiles/models.go
- backend/profiles/service.go
1. Users should be able to delete their profile permanently closes #176 
2. refactor: improved readability and optimized the community APIs.
> feat, refactor, fix: DeleteProfile API + delete user functionality, optimized most of the API in profiles, communities

- README.md
- Sprint3.md
- backend/communities/service.go
Created Sprint3.md to document accomplishments of Sprint3.
Updated Readme with Sprint3 section.
Changed non-post http methods to post for communities APIs
Temporary change to accommodate limitations of frontend API calling library.
TODO: Change these APIs back to their original http methods by having query strings for GET and DELETE methods.
> docs,chore: created sprint3.md and updated readme, changed non-post http methods to post

- backend/communities/service.go
> feat: api to get all communities

- frontend/forum-app/src/app/subreddits.service.ts
- frontend/forum-app/src/app/subreddits/subreddits.component.html
- frontend/forum-app/src/app/subreddits/subreddits.component.ts
Subreddits view is now connected to database
> feat: subreddits are now pulled from database

- backend/comments/models.go
- backend/comments/service.go
- backend/common/error_msgs.go
- backend/communities/service.go
- backend/posts/models.go
> feat,fix: new api to get comments for post, voting bug fixed

- backend/posts/models.go
- backend/posts/service.go
- backend/profiles/models.go
- backend/profiles/service.go
1.  The user should be able to upvote and downvote a post closes #207
2. Users should be able to save comments or posts closes #210
3. The Method used for DeleteProfile and DeletePost has been changed #211
> feat: Vote API + Readability

- backend/tests/comments_tests.go
- backend/tests/profile_tests.go
- backend/tests/saved_tests.go
1. Created test cases for Profiles GetProfile, DeleteProfile, and Edit Profile closes #228 
2. Created Test cases for DeletePost, UpDownVote Post, Edit Post, and CreatePost closes #229 
3. Created Test cases for savedComments that saves comments closes #230
> gotests: test cases for profiles,post and saved

- backend/comments/models.go
- backend/comments/service.go
- backend/tests/comments_test.go
- backend/tests/main_test.go
- backend/tests/posts_test.go
> test: tests for create, get, vote and delete comments

- backend/communities/service.go
- backend/profiles/service.go
- backend/users/models.go
- backend/users/service.go
1.  The user should be able to get subscriptions of what all communities user is following closes #251 
2. The user should be able to subscribe to a community closes #252 
3. The user should be able to save a post to their profile closes #254
> feat : GetSubcriptions and UpdateSubscriptions

- backend/profiles/models.go
- backend/profiles/service.go
1.  User should be able to see their saved posts in the profile section closes #258
> feat, enhancement: Created GetSavedPosts API, enhanced UpdateSavedPosts and UpdateSavedComments API

- .github/ISSUE_TEMPLATE/user-story.md
Changed formatting to headings instead of bold.
Added sample tasks for quick task writing.
> docs: made user story issue template more markdown friendly

- appspec.yml
AWS Deployment AppSpec.yml created.
AWS EC2 AWSCodeDeploy roles added in AWS Console.
For AppSpec, took help from aws repo:
<https://github.com/amazon-archives/golang-deployment-pipeline>
Completes task for Issue #269
> ci: aws deployment appspec file added

- .github/workflows/ci-cd-pipeline.yml
Added AWS access id and secret key to Github secrets.
Completes "create github workflow" task in issue #269
> Created gihtub workflow for ci/cd

- .github/workflows/ci-cd-aws.yml
- appspec.yml
- scripts/after_install.sh
- scripts/before_install.sh
- scripts/install_dependencies.sh
> ci: updated install scripts, added role to assume in workflow

- frontend/forum-app/src/app/app.component.ts
- frontend/forum-app/src/styles.css
- frontend/forum-app/tsconfig.json
Pages are now responsive to resizable window dimensions
> fix: Responsive pages

- backend/communities/service.go
- backend/profiles/service.go
1.  Fixed the validation block for the API closes #292 
2. Check-name API should be fixed closes #293
> fix : checkname API and GetCommunity API

- CODE_OF_CONDUCT.md
Write the code of conduct for contributors of the community closes #300
> Create CODE OF CONDUCT for Contributors

- README.md
Url to deployed website added to documentation.
> docs: added aws ci/cd workflow badge, app url

- Sprint4.md
Created Sprint4.md and added a basic structure.
> docs: added Sprint4.md structure

- backend/profiles/models.go
1.  Modified responses for saved post APIs #340 
2. Modified responses for saved comment APIs #341
> bugfix, fix: Saved Items API Reponses modified

- README.md
Go Tests Github Action Badge added to Readme.md
> docs: added go tests badge, formatting

- backend/posts/models.go
- backend/posts/service.go
> fix: unlimited votes by single user, only creator can vote

- backend/comments/service.go
- backend/tests/comments_test.go
> fix: comment delete route changed to POST method

- Sprint4.md
> docs: added short Testing Video and API Demo video
